version: '3.9'

services:

  frontend-react:
    image: koitoror-university-frontend
    build:
      context: ./frontend/
      # args:
        # NODE_ENV: development
    command: npm run dev
    # command: npm start
    ports:
      - 5000:3000 #developoment
      # - 5000:5000 #production
    volumes:
      - ./frontend/:/app
      # - /frontend/node_modules:/app/node_modules
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_NODE_ENV=development
      - SESSION_SECRET=secret

  backend-django-app:
    # image: koitoror-university-backend
    build:
      context: .
      # dockerfile: Dockerfile.dev
    command: >
      sh -c "python backend/manage.py wait_for_db &&
             python backend/manage.py migrate &&
             python backend/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
      - ./frontend/:/frontend
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme

    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
