version: '3.9'

services:
  app:
    image: koitoror-university:1.0.6
    build:
      context: .
      # dockerfile: Dockerfile.dev
    command: >
      sh -c "python backend/manage.py wait_for_db &&
             python backend/manage.py migrate &&
             python backend/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
      - ./data/web:/vol/web
      # - ./:/
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - ALLOWED_HOSTS_DEV=${ALLOWED_HOSTS_DEV}
      - CORS_ORIGIN_WHITELIST=${CORS_ORIGIN_WHITELIST}

    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
