version: '3.9'

services:

  frontend-react:
    image: koitoror-university-frontend:2.1.0
    # image: koitoror-university-frontend
    build:
      context: ./frontend/
      args:
        NODE_ENV: development
    command: npm run dev
    # command: >
    #   sh -c "npm run postbuild &&
    #          npm run dev"
    # command: npm start
    ports:
      - 5000:3000 #developoment
      # - 5000:5000 #production
    volumes:
      - ./frontend/:/app

      # - ./frontend/node_modules:/app/node_modules # run from local
      - ./node_modules:/app/node_modules
      # - ./package.json:/app/package.json

      # - /app/node_modules # run from image and copy to local (cp -b -r node_module)
      # - /app/build

    environment:
      - NODE_ENV=development
      - REACT_APP_NODE_ENV=development
      - SESSION_SECRET=secret

  backend-django-app:
    image: koitoror-university-backend:2.0.3
    # image: koitoror-university-backend
    build:
      context: ./backend/
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./backend:/backend
      - ./frontend/build:/frontend/build
      - ./data/web:/vol/web
    command: >
      sh -c "python backend/manage.py wait_for_db &&
             python backend/manage.py migrate &&
             python backend/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - SECRET_KEY=devsecretkey
      - DEBUG=1

    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    depends_on:
      - frontend-react

prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
