global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: monitoring
    metrics_path: /metrics
    static_configs:
      - targets:
        - frontend-react:5000
        - backend-django-app:8000
        - backend-django-app2:8001
        - db:8001
        - db2:8001
