# Generated by Django 3.2.11 on 2022-02-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='is_student'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_teacher',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is_teacher'),
        ),
    ]
